<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type">
<title>TCustomApplication.HandleException</title>
<link rel="stylesheet" href="../fpdoc.css" type="text/css">

</head>
<body>
<table class="bar" width="100%" border="0" cellpadding="4" cellspacing="0">
<tr>
<td><b>[<a href="../custapp/index.html">Overview</a>][<a href="../custapp/index-3.html">Types</a>][<a href="../custapp/index-4.html">Classes</a>][<a href="../custapp/index-6.html">Variables</a>][<a href="../custapp/index-8.html">Index</a>]</b></td>
<td align="right"><span class="bartitle">Reference for unit 'CustApp' (<a href="../index.html">#fcl</a>)</span></td>
</tr>
</table>
<h1>TCustomApplication.HandleException</h1>
<p>Handle an exception.</p>
<h2>Declaration</h2>
<p>Source position: custapp.pp line 63</p>
<table cellpadding="0" cellspacing="0">
<tr>
<td><p><tt><span class="code"> <span class="kw">public</span> <span class="kw">procedure</span> <a href="../custapp/tcustomapplication.html">TCustomApplication</a><span class="sym">.</span>HandleException<span class="sym">(</span></span></tt></p></td>
</tr>
<tr>
<td><p><tt><span class="code">&nbsp;&nbsp;Sender<span class="sym">: </span><a href="../../rtl/system/tobject.html">TObject</a></span></tt></p></td>
</tr>
<tr>
<td><p><tt><span class="code"><span class="sym">)</span><span class="sym">;</span><span class="kw"> virtual</span><span class="sym">;</span></span></tt></p></td>
</tr>
</table>
<h2>Arguments</h2>
<table cellpadding="0" cellspacing="0">
<tr>
<td valign="top"><p><tt><span class="code">Sender</span></tt></p></td>
<td><p>&nbsp;&nbsp;</p></td>
<td><p class="cmt">Sender class calling this routine</p></td>
</tr>
</table>
<h2>Description</h2>
<p><var>HandleException</var> is called (or can be called) to  handle the exception <var>Sender</var>. If the exception is not of class <var>Exception</var> then the default handling of exceptions in the <span class="file">SysUtils</span> unit is called. </p>
<p>If the exception is of class <var>Exception</var> and the <a href="../custapp/tcustomapplication.onexception.html">OnException</a> handler  is set, the handler is called with the exception object and <var>Sender</var> argument. </p>
<p>If the <var>OnException</var> handler is not set, then the exception is passed to the <a href="../custapp/tcustomapplication.showexception.html">ShowException</a>  routine, which can be overridden by descendent application classes to  show the exception in a way that is fit for the particular class of application. (a GUI application might show the exception in a message dialog. </p>
<p>When the exception is handled in the above manner, and the <a href="../custapp/tcustomapplication.stoponexception.html">StopOnException</a> property is set to <var>True</var>, the <a href="../custapp/tcustomapplication.terminated.html">Terminated</a> property is set to <var>True</var>, which will cause the <a href="../custapp/tcustomapplication.run.html">Run</a> loop to stop, and the application will exit. </p>
<h2>See also</h2>
<table cellpadding="0" cellspacing="0">
<tr>
<td valign="top"><p><a href="../custapp/tcustomapplication.showexception.html">ShowException</a></p></td>
<td><p>&nbsp;&nbsp;</p></td>
<td><p class="cmt">Show an exception to the user</p></td>
</tr>
<tr>
<td valign="top"><p><a href="../custapp/tcustomapplication.stoponexception.html">StopOnException</a></p></td>
<td><p>&nbsp;&nbsp;</p></td>
<td><p class="cmt">Should the program loop stop on an exception</p></td>
</tr>
<tr>
<td valign="top"><p><a href="../custapp/tcustomapplication.terminated.html">Terminated</a></p></td>
<td><p>&nbsp;&nbsp;</p></td>
<td><p class="cmt">Was <var>Terminate</var> called or not</p></td>
</tr>
<tr>
<td valign="top"><p><a href="../custapp/tcustomapplication.run.html">Run</a></p></td>
<td><p>&nbsp;&nbsp;</p></td>
<td><p class="cmt">Runs the application.</p></td>
</tr>
</table>
<hr>

<span class="footer">Documentation generated on: Sep 28 2017</span>
</body>
</html>
