<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<title>libstdc++: Exceptions</title>

<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>


</head>
<body>
<div id="top"><!-- do not remove this div! -->


<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  
  
  <td style="padding-left: 0.5em;">
   <div id="projectname">libstdc++
   
   </div>
   
  </td>
  
  
  
   
  
 </tr>
 </tbody>
</table>
</div>

<!-- Generated by Doxygen 1.7.6.1 -->
</div>
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
  initNavTree('a01602.html','');
</script>
<div id="doc-content">
<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#typedef-members">Typedefs</a> &#124;
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">Exceptions</div>  </div>
<div class="ingroups"><a class="el" href="a01600.html">Diagnostics</a></div></div><!--header-->
<div class="contents">
<div class="dynheader">
Collaboration diagram for Exceptions:</div>
<div class="dyncontent">
<center><table><tr><td><img src="a01602.png" border="0" alt="" usemap="#a01602"/>
<map name="a01602" id="a01602">
<area shape="rect" id="node1" href="a01600.html" title="Diagnostics" alt="" coords="7,7,100,35"/><area shape="rect" id="node3" href="a01606.html" title="Futures" alt="" coords="395,7,464,35"/></map>
</td></tr></table></center>
</div>
<h2><a name="nested-classes"></a>
Classes</h2>
<ul>
<li>class <a class="el" href="a00005.html">__cxxabiv1::__forced_unwind</a>
<dl class="el"><dd class="mdescRight">Thrown as part of forced unwinding.A magic placeholder class that can be caught by reference to recognize forced unwinding.  <a href="a00005.html#details">More...</a><br/></dl><li>struct <a class="el" href="a00045.html">__gnu_cxx::forced_error</a>
<dl class="el"><dd class="mdescRight">Thown by exception safety machinery.  <a href="a00045.html#details">More...</a><br/></dl><li>class <a class="el" href="a00064.html">__gnu_cxx::recursive_init_error</a>
<dl class="el"><dd class="mdescRight">Exception thrown by __cxa_guard_acquire.6.7[stmt.dcl]/4: If control re-enters the declaration (recursively) while the object is being initialized, the behavior is undefined.  <a href="a00064.html#details">More...</a><br/></dl><li>class <a class="el" href="a00468.html">std::__exception_ptr::exception_ptr</a>
<dl class="el"><dd class="mdescRight">An opaque pointer to an arbitrary exception.  <a href="a00468.html#details">More...</a><br/></dl><li>class <a class="el" href="a00558.html">std::bad_alloc</a>
<dl class="el"><dd class="mdescRight">Exception possibly thrown by <code>new</code>.<code><a class="el" href="a00558.html" title="Exception possibly thrown by new.bad_alloc (or classes derived from it) is used to report allocation ...">bad_alloc</a></code> (or classes derived from it) is used to report allocation errors from the throwing forms of <code>new</code>.  <a href="a00558.html#details">More...</a><br/></dl><li>class <a class="el" href="a00559.html">std::bad_cast</a>
<dl class="el"><dd class="mdescRight">Thrown during incorrect typecasting.If you attempt an invalid <code>dynamic_cast</code> expression, an instance of this class (or something derived from this class) is thrown.  <a href="a00559.html#details">More...</a><br/></dl><li>class <a class="el" href="a00560.html">std::bad_exception</a>
<li>class <a class="el" href="a00561.html">std::bad_function_call</a>
<dl class="el"><dd class="mdescRight">Exception class thrown when class template function's operator() is called with an empty target.  <a href="a00561.html#details">More...</a><br/></dl><li>class <a class="el" href="a00562.html">std::bad_typeid</a>
<dl class="el"><dd class="mdescRight">Thrown when a NULL pointer in a <code>typeid</code> expression is used.  <a href="a00562.html#details">More...</a><br/></dl><li>class <a class="el" href="a00563.html">std::bad_weak_ptr</a>
<dl class="el"><dd class="mdescRight">Exception possibly thrown by <code><a class="el" href="a00450.html" title="A smart pointer with reference-counted copy semantics.">shared_ptr</a></code>.  <a href="a00563.html#details">More...</a><br/></dl><li>class <a class="el" href="a00632.html">std::domain_error</a>
<li>class <a class="el" href="a00638.html">std::exception</a>
<dl class="el"><dd class="mdescRight">Base class for all library exceptions.  <a href="a00638.html#details">More...</a><br/></dl><li>class <a class="el" href="a00651.html">std::future_error</a>
<dl class="el"><dd class="mdescRight">Exception type thrown by futures.  <a href="a00651.html#details">More...</a><br/></dl><li>class <a class="el" href="a00711.html">std::invalid_argument</a>
<li>class <a class="el" href="a00713.html">std::ios_base::failure</a>
<dl class="el"><dd class="mdescRight">These are thrown to indicate problems with io.27.4.2.1.1 Class <a class="el" href="a00713.html" title="These are thrown to indicate problems with io.27.4.2.1.1 Class ios_base::failure.">ios_base::failure</a>.  <a href="a00713.html#details">More...</a><br/></dl><li>class <a class="el" href="a00777.html">std::length_error</a>
<li>class <a class="el" href="a00785.html">std::logic_error</a>
<dl class="el"><dd class="mdescRight">One of two subclasses of exception.  <a href="a00785.html#details">More...</a><br/></dl><li>class <a class="el" href="a00817.html">std::nested_exception</a>
<dl class="el"><dd class="mdescRight">Exception class with exception_ptr data member.  <a href="a00817.html#details">More...</a><br/></dl><li>class <a class="el" href="a00846.html">std::out_of_range</a>
<li>class <a class="el" href="a00848.html">std::overflow_error</a>
<li>class <a class="el" href="a00867.html">std::range_error</a>
<li>class <a class="el" href="a00877.html">std::regex_error</a>
<dl class="el"><dd class="mdescRight">A regular expression exception class.The regular expression library throws objects of this class on error.  <a href="a00877.html#details">More...</a><br/></dl><li>class <a class="el" href="a00888.html">std::runtime_error</a>
<dl class="el"><dd class="mdescRight">One of two subclasses of exception.  <a href="a00888.html#details">More...</a><br/></dl><li>class <a class="el" href="a00896.html">std::system_error</a>
<dl class="el"><dd class="mdescRight">Thrown to indicate error code of underlying system.  <a href="a00896.html#details">More...</a><br/></dl><li>class <a class="el" href="a00922.html">std::underflow_error</a>
</ul>
<h2><a name="typedef-members"></a>
Typedefs</h2>
<ul>
<li>typedef void(* <a class="el" href="a01602.html#gac6afb78180be4f4f841ae9d32f538f00">std::terminate_handler</a> )()
<li>typedef void(* <a class="el" href="a01602.html#gaeeec922393be8c20662a12875c1d09f0">std::unexpected_handler</a> )()
</ul>
<h2><a name="func-members"></a>
Functions</h2>
<ul>
<li><a class="anchor" id="ga67ba96bcef76a5e9bed692e3a974946c"></a><!-- doxytag: member="exceptions::__get_nested_exception" ref="ga67ba96bcef76a5e9bed692e3a974946c" args="(const _Ex &amp;__ex)" -->
template&lt;typename _Ex &gt; const nested_exception * <b>std::__get_nested_exception</b> (const _Ex &amp;__ex)
<li><a class="anchor" id="gac0725df8c0e8ed804d3953e26c9730f6"></a><!-- doxytag: member="exceptions::__throw_with_nested" ref="gac0725df8c0e8ed804d3953e26c9730f6" args="(_Ex &amp;&amp;, const nested_exception *=0) __attribute__((__noreturn__))" -->
template&lt;typename _Ex &gt; void <b>std::__throw_with_nested</b> (_Ex &amp;&amp;, const nested_exception *=0) __attribute__((__noreturn__))
<li><a class="anchor" id="gaca7174ffb4dbcacb78a826ab02919591"></a><!-- doxytag: member="exceptions::__throw_with_nested" ref="gaca7174ffb4dbcacb78a826ab02919591" args="(_Ex &amp;&amp;,...) __attribute__((__noreturn__))" -->
template&lt;typename _Ex &gt; void <b>std::__throw_with_nested</b> (_Ex &amp;&amp;,...) __attribute__((__noreturn__))
<li>void <a class="el" href="a01602.html#gaf51888cedbc669a114cd79e39e0cd9be">__gnu_cxx::__verbose_terminate_handler</a> ()
<li>template&lt;typename _Ex &gt; exception_ptr <a class="el" href="a01602.html#gac77b7cd99c9c835996481e929f1db9c0">std::copy_exception</a> (_Ex __ex) _GLIBCXX_USE_NOEXCEPT
<li>exception_ptr <a class="el" href="a01602.html#gafcca609a0e064086e3d37ff25c85ab69">std::current_exception</a> () _GLIBCXX_USE_NOEXCEPT
<li>template&lt;typename _Ex &gt; exception_ptr <a class="el" href="a01602.html#ga3fcf872bf90a82af0c0ce957c0611b1f">std::make_exception_ptr</a> (_Ex __ex) _GLIBCXX_USE_NOEXCEPT
<li>void <a class="el" href="a01602.html#ga64d0b68338d7edbfd7d95f4177dbc442">std::rethrow_exception</a> (exception_ptr) __attribute__((__noreturn__))
<li>template&lt;typename _Ex &gt; void <a class="el" href="a01602.html#gab61c4f8fae83699092207e16594f6b35">std::rethrow_if_nested</a> (const _Ex &amp;__ex)
<li>void <a class="el" href="a01602.html#gafdde517cbb3891421e60bff1d733e8dd">std::rethrow_if_nested</a> (const nested_exception &amp;__ex)
<li>terminate_handler <a class="el" href="a01602.html#gad878869876802a045479b446bfe2f1f2">std::set_terminate</a> (terminate_handler) _GLIBCXX_USE_NOEXCEPT
<li>unexpected_handler <a class="el" href="a01602.html#gaf79e744b0aa5a665e96331a57bb3a867">std::set_unexpected</a> (unexpected_handler) _GLIBCXX_USE_NOEXCEPT
<li>void <a class="el" href="a01602.html#ga39553839b12d33d09a4e450a393789ce">std::terminate</a> () _GLIBCXX_USE_NOEXCEPT __attribute__((__noreturn__))
<li>template&lt;typename _Ex &gt; void <a class="el" href="a01602.html#gabb5c9444dfac00145f90c2a75c52116e">std::throw_with_nested</a> (_Ex __ex)
<li>bool <a class="el" href="a01602.html#ga6e2ca8f06b3d2fd0ba35addd2ec6a860">std::uncaught_exception</a> () _GLIBCXX_USE_NOEXCEPT __attribute__((__pure__))
<li>void <a class="el" href="a01602.html#ga742bf00b19772819acc97ae5e8f4bebe">std::unexpected</a> () __attribute__((__noreturn__))
</ul>
<hr/><a name="details" id="details"></a><h2>Detailed Description</h2>
<p>Classes and functions for reporting errors via exception classes. </p>
<hr/><h2>Typedef Documentation</h2>
<a class="anchor" id="gac6afb78180be4f4f841ae9d32f538f00"></a><!-- doxytag: member="std::terminate_handler" ref="gac6afb78180be4f4f841ae9d32f538f00" args=")()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">typedef void(* <a class="el" href="a01602.html#gac6afb78180be4f4f841ae9d32f538f00">std::terminate_handler</a>)()</td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>If you write a replacement terminate handler, it must be of this type. </p>

<p>Definition at line <a class="el" href="a01138_source.html#l00089">89</a> of file <a class="el" href="a01138_source.html">exception</a>.</p>

</div>
</div>
<a class="anchor" id="gaeeec922393be8c20662a12875c1d09f0"></a><!-- doxytag: member="std::unexpected_handler" ref="gaeeec922393be8c20662a12875c1d09f0" args=")()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">typedef void(* <a class="el" href="a01602.html#gaeeec922393be8c20662a12875c1d09f0">std::unexpected_handler</a>)()</td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>If you write a replacement unexpected handler, it must be of this type. </p>

<p>Definition at line <a class="el" href="a01138_source.html#l00092">92</a> of file <a class="el" href="a01138_source.html">exception</a>.</p>

</div>
</div>
<hr/><h2>Function Documentation</h2>
<a class="anchor" id="gaf51888cedbc669a114cd79e39e0cd9be"></a><!-- doxytag: member="__gnu_cxx::__verbose_terminate_handler" ref="gaf51888cedbc669a114cd79e39e0cd9be" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="a01602.html#gaf51888cedbc669a114cd79e39e0cd9be">__gnu_cxx::__verbose_terminate_handler</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>A replacement for the standard terminate_handler which prints more information about the terminating exception (if any) on stderr. </p>
<p>Call </p>
<div class="fragment"><pre class="fragment">     <a class="code" href="a01602.html#gad878869876802a045479b446bfe2f1f2" title="Takes a new handler function as an argument, returns the old function.">std::set_terminate</a>(<a class="code" href="a01602.html#gaf51888cedbc669a114cd79e39e0cd9be" title="A replacement for the standard terminate_handler which prints more information about the terminating ...">__gnu_cxx::__verbose_terminate_handler</a>)
</pre></div><p> to use. For more info, see <a href="http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt02ch06s02.html">http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt02ch06s02.html</a></p>
<p>In 3.4 and later, this is on by default. </p>

</div>
</div>
<a class="anchor" id="gac77b7cd99c9c835996481e929f1db9c0"></a><!-- doxytag: member="std::copy_exception" ref="gac77b7cd99c9c835996481e929f1db9c0" args="(_Ex __ex) _GLIBCXX_USE_NOEXCEPT" -->
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;typename _Ex &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">exception_ptr <a class="el" href="a01602.html#gac77b7cd99c9c835996481e929f1db9c0">std::copy_exception</a> </td>
          <td>(</td>
          <td class="paramtype">_Ex&#160;</td>
          <td class="paramname"><em>__ex</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Obtain an exception_ptr pointing to a copy of the supplied object. </p>

<p>Definition at line <a class="el" href="a01141_source.html#l00169">169</a> of file <a class="el" href="a01141_source.html">exception_ptr.h</a>.</p>

<p>References <a class="el" href="a01602.html#gafcca609a0e064086e3d37ff25c85ab69">std::current_exception()</a>.</p>

</div>
</div>
<a class="anchor" id="gafcca609a0e064086e3d37ff25c85ab69"></a><!-- doxytag: member="std::current_exception" ref="gafcca609a0e064086e3d37ff25c85ab69" args="() _GLIBCXX_USE_NOEXCEPT" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">exception_ptr <a class="el" href="a01602.html#gafcca609a0e064086e3d37ff25c85ab69">std::current_exception</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>Obtain an exception_ptr to the currently handled exception. If there is none, or the currently handled exception is foreign, return the null value. </p>

<p>Referenced by <a class="el" href="a01141_source.html#l00169">std::copy_exception()</a>.</p>

</div>
</div>
<a class="anchor" id="ga3fcf872bf90a82af0c0ce957c0611b1f"></a><!-- doxytag: member="std::make_exception_ptr" ref="ga3fcf872bf90a82af0c0ce957c0611b1f" args="(_Ex __ex) _GLIBCXX_USE_NOEXCEPT" -->
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;typename _Ex &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">exception_ptr <a class="el" href="a01602.html#ga3fcf872bf90a82af0c0ce957c0611b1f">std::make_exception_ptr</a> </td>
          <td>(</td>
          <td class="paramtype">_Ex&#160;</td>
          <td class="paramname"><em>__ex</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Obtain an exception_ptr pointing to a copy of the supplied object. </p>

<p>Definition at line <a class="el" href="a01141_source.html#l00188">188</a> of file <a class="el" href="a01141_source.html">exception_ptr.h</a>.</p>

</div>
</div>
<a class="anchor" id="ga64d0b68338d7edbfd7d95f4177dbc442"></a><!-- doxytag: member="std::rethrow_exception" ref="ga64d0b68338d7edbfd7d95f4177dbc442" args="(exception_ptr) __attribute__((__noreturn__))" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="a01602.html#ga64d0b68338d7edbfd7d95f4177dbc442">std::rethrow_exception</a> </td>
          <td>(</td>
          <td class="paramtype">exception_ptr&#160;</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Throw the object pointed to by the exception_ptr. </p>

</div>
</div>
<a class="anchor" id="gab61c4f8fae83699092207e16594f6b35"></a><!-- doxytag: member="std::rethrow_if_nested" ref="gab61c4f8fae83699092207e16594f6b35" args="(const _Ex &amp;__ex)" -->
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;typename _Ex &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="a01602.html#gab61c4f8fae83699092207e16594f6b35">std::rethrow_if_nested</a> </td>
          <td>(</td>
          <td class="paramtype">const _Ex &amp;&#160;</td>
          <td class="paramname"><em>__ex</em></td><td>)</td>
          <td><code> [inline]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>If <code>__ex</code> is derived from <a class="el" href="a00817.html" title="Exception class with exception_ptr data member.">nested_exception</a>, <code>__ex.rethrow_nested()</code>. </p>

<p>Definition at line <a class="el" href="a01294_source.html#l00146">146</a> of file <a class="el" href="a01294_source.html">nested_exception.h</a>.</p>

</div>
</div>
<a class="anchor" id="gafdde517cbb3891421e60bff1d733e8dd"></a><!-- doxytag: member="std::rethrow_if_nested" ref="gafdde517cbb3891421e60bff1d733e8dd" args="(const nested_exception &amp;__ex)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="a01602.html#gab61c4f8fae83699092207e16594f6b35">std::rethrow_if_nested</a> </td>
          <td>(</td>
          <td class="paramtype">const nested_exception &amp;&#160;</td>
          <td class="paramname"><em>__ex</em></td><td>)</td>
          <td><code> [inline]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Overload, See N2619. </p>

<p>Definition at line <a class="el" href="a01294_source.html#l00154">154</a> of file <a class="el" href="a01294_source.html">nested_exception.h</a>.</p>

</div>
</div>
<a class="anchor" id="gad878869876802a045479b446bfe2f1f2"></a><!-- doxytag: member="std::set_terminate" ref="gad878869876802a045479b446bfe2f1f2" args="(terminate_handler) _GLIBCXX_USE_NOEXCEPT" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">terminate_handler <a class="el" href="a01602.html#gad878869876802a045479b446bfe2f1f2">std::set_terminate</a> </td>
          <td>(</td>
          <td class="paramtype">terminate_handler&#160;</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Takes a new handler function as an argument, returns the old function. </p>

</div>
</div>
<a class="anchor" id="gaf79e744b0aa5a665e96331a57bb3a867"></a><!-- doxytag: member="std::set_unexpected" ref="gaf79e744b0aa5a665e96331a57bb3a867" args="(unexpected_handler) _GLIBCXX_USE_NOEXCEPT" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">unexpected_handler <a class="el" href="a01602.html#gaf79e744b0aa5a665e96331a57bb3a867">std::set_unexpected</a> </td>
          <td>(</td>
          <td class="paramtype">unexpected_handler&#160;</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Takes a new handler function as an argument, returns the old function. </p>

</div>
</div>
<a class="anchor" id="ga39553839b12d33d09a4e450a393789ce"></a><!-- doxytag: member="std::terminate" ref="ga39553839b12d33d09a4e450a393789ce" args="() _GLIBCXX_USE_NOEXCEPT __attribute__((__noreturn__))" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="a01602.html#ga39553839b12d33d09a4e450a393789ce">std::terminate</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>The runtime will call this function if exception handling must be abandoned for any reason. It can also be called by the user. </p>

</div>
</div>
<a class="anchor" id="gabb5c9444dfac00145f90c2a75c52116e"></a><!-- doxytag: member="std::throw_with_nested" ref="gabb5c9444dfac00145f90c2a75c52116e" args="(_Ex __ex)" -->
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;typename _Ex &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="a01602.html#gabb5c9444dfac00145f90c2a75c52116e">std::throw_with_nested</a> </td>
          <td>(</td>
          <td class="paramtype">_Ex&#160;</td>
          <td class="paramname"><em>__ex</em></td><td>)</td>
          <td><code> [inline]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>If <code>__ex</code> is derived from <a class="el" href="a00817.html" title="Exception class with exception_ptr data member.">nested_exception</a>, <code>__ex</code>. Else, an implementation-defined object derived from both. </p>

<p>Definition at line <a class="el" href="a01294_source.html#l00136">136</a> of file <a class="el" href="a01294_source.html">nested_exception.h</a>.</p>

</div>
</div>
<a class="anchor" id="ga6e2ca8f06b3d2fd0ba35addd2ec6a860"></a><!-- doxytag: member="std::uncaught_exception" ref="ga6e2ca8f06b3d2fd0ba35addd2ec6a860" args="() _GLIBCXX_USE_NOEXCEPT __attribute__((__pure__))" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="a01602.html#ga6e2ca8f06b3d2fd0ba35addd2ec6a860">std::uncaught_exception</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>[18.6.4]/1: 'Returns true after completing evaluation of a throw-expression until either completing initialization of the exception-declaration in the matching handler or entering <code><a class="el" href="a01602.html#ga742bf00b19772819acc97ae5e8f4bebe">unexpected()</a></code> due to the throw; or after entering <code><a class="el" href="a01602.html#ga39553839b12d33d09a4e450a393789ce">terminate()</a></code> for any reason other than an explicit call to <code><a class="el" href="a01602.html#ga39553839b12d33d09a4e450a393789ce">terminate()</a></code>. [Note: This includes stack unwinding [15.2]. end note]'</p>
<p>2: 'When <code><a class="el" href="a01602.html#ga6e2ca8f06b3d2fd0ba35addd2ec6a860">uncaught_exception()</a></code> is true, throwing an exception can result in a call of <code><a class="el" href="a01602.html#ga39553839b12d33d09a4e450a393789ce">terminate()</a></code> (15.5.1).' </p>

<p>Referenced by <a class="el" href="a01315_source.html#l00426">std::basic_ostream&lt; _CharT, _Traits &gt;::sentry::~sentry()</a>.</p>

</div>
</div>
<a class="anchor" id="ga742bf00b19772819acc97ae5e8f4bebe"></a><!-- doxytag: member="std::unexpected" ref="ga742bf00b19772819acc97ae5e8f4bebe" args="() __attribute__((__noreturn__))" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="a01602.html#ga742bf00b19772819acc97ae5e8f4bebe">std::unexpected</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>The runtime will call this function if an exception is thrown which violates the function's exception specification. </p>

</div>
</div>
</div><!-- contents -->
</div>
  <div id="nav-path" class="navpath">
    <ul>

    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.7.6.1 </li>
   </ul>
 </div>


</body>
</html>
